# Generated by Django 4.0.4 on 2022-05-25 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='keys',
            fields=[
                ('key', models.CharField(max_length=100)),
                ('id1', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=100)),
                ('id1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_project.keys')),
            ],
        ),
    ]
